DROP TABLE IF EXISTS CONSOLIDATED_FW;
DROP TABLE IF EXISTS SSCD_CISPEC;
DROP TABLE IF EXISTS SSCD_CI_SECURITY;
DROP TABLE IF EXISTS SSCD_CI_SECURITY_IP;
DROP TABLE IF EXISTS PORTAL_SOC_FW;
DROP TABLE IF EXISTS RANCID_DEVICES;
DROP TABLE IF EXISTS ARP;

CREATE TABLE SSCD_CISPEC (
    CISPECID VARCHAR (60),
    ALNVALUE VARCHAR (1500),
    ASSETATTRID VARCHAR (500),
    CINUM VARCHAR (500),
    CHANGEDATE TEXT
);

CREATE TABLE SSCD_CI_SECURITY (
    CONFIG_ITEM VARCHAR (500),
    CLASS_ID VARCHAR (60),
    CLASS_DESC VARCHAR (500),
    LOCATION_ID VARCHAR (1500),
    LOCATION_DESC VARCHAR (1500),
    LOCATION_COUNTRY VARCHAR (500),
    LOCATION_ADDRESS VARCHAR (1500),
    CUSTOMER_ID VARCHAR (60),
    CUSTOMER_NAME VARCHAR (500)
);

CREATE TABLE SSCD_CI_SECURITY_IP (
    CONFIG_ITEM_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CONFIG_ITEM VARCHAR (500),
    CLASS_ID VARCHAR (60),
    CLASS_DESC VARCHAR (500),
    LOCATION_ID VARCHAR (1500),
    LOCATION_DESC VARCHAR (1500),
    LOCATION_COUNTRY VARCHAR (500),
    LOCATION_ADDRESS VARCHAR (1500),
    CUSTOMER_ID VARCHAR (60),
    CUSTOMER_NAME VARCHAR (500),
    SPEC_VALUE VARCHAR (500),
    SPEC_DESC VARCHAR (500),
    IP VARCHAR (500),
    ANSWER_PING INTEGER,
    NMAP_PORTS VARCHAR(500),
    LOGIN_MGT VARCHAR(60),
    OS_VERSION VARCHAR(500)
);

CREATE TABLE PORTAL_SOC_FW (
    CID VARCHAR (60),
    CUSTOMER VARCHAR (500),
    LOCATION_DESC VARCHAR (1500),
    IP_DCN VARCHAR (500),
    IP_PUBLIC VARCHAR (500),
    MGT_PORT VARCHAR (60),
    SN VARCHAR (500),
    OSVERSION VARCHAR (500),
    LIC_EXPIRATION VARCHAR (500)
);

CREATE TABLE RANCID_DEVICES (
    CID VARCHAR (60),
    CIDNUM VARCHAR (60),
    CUSTOMER VARCHAR (500),
    LOCATION_DESC VARCHAR (1500),
    IP_DCN VARCHAR (500),
    OSVERSION VARCHAR (500),
    VENDOR VARCHAR (60)
);

