DROP TABLE IF EXISTS CONSOLIDATED_FW;
DROP TABLE IF EXISTS SSCD_CISPEC;
DROP TABLE IF EXISTS SSCD_CI_SECURITY;
DROP TABLE IF EXISTS SSCD_CI_SECURITY_IP;
DROP TABLE IF EXISTS SSCD_CI_SECURITY_IP_TRANSITION;
DROP TABLE IF EXISTS PORTAL_SOC_FW;
DROP TABLE IF EXISTS PORTAL_SOC_FW_TRANSITION;
DROP TABLE IF EXISTS RANCID_DEVICES;
DROP TABLE IF EXISTS ARP;

CREATE TABLE SSCD_CISPEC (
    CISPECID TEXT,
    ALNVALUE TEXT,
    ASSETATTRID TEXT,
    CINUM TEXT,
    CHANGEDATE TEXT
);

CREATE TABLE SSCD_CI_SECURITY (
    CONFIG_ITEM TEXT,
    CLASS_ID TEXT,
    CLASS_DESC TEXT,
    LOCATION_ID TEXT,
    LOCATION_DESC TEXT,
    LOCATION_COUNTRY TEXT,
    LOCATION_ADDRESS TEXT,
    CUSTOMER_ID TEXT,
    CUSTOMER_NAME TEXT
);

CREATE TABLE SSCD_CI_SECURITY_IP_TRANSITION (
    CONFIG_ITEM_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CONFIG_ITEM TEXT,
    CLASS_ID TEXT,
    CLASS_DESC TEXT,
    LOCATION_ID TEXT,
    LOCATION_DESC TEXT,
    LOCATION_COUNTRY TEXT,
    LOCATION_ADDRESS TEXT,
    CUSTOMER_ID TEXT,
    CUSTOMER_NAME TEXT,
    SPEC_VALUE TEXT,
    SPEC_DESC TEXT,
    IP TEXT
);

CREATE TABLE SSCD_CI_SECURITY_IP (
    CONFIG_ITEM_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CONFIG_ITEM TEXT,
    CLASS_ID TEXT,
    CLASS_DESC TEXT,
    LOCATION_ID TEXT,
    LOCATION_DESC TEXT,
    LOCATION_COUNTRY TEXT,
    LOCATION_ADDRESS TEXT,
    CUSTOMER_ID TEXT,
    CUSTOMER_NAME TEXT,
    SPEC_VALUE TEXT,
    SPEC_DESC TEXT,
    IP TEXT,
    PING_ANSWER INTEGER,
    NMAP_PORTS TEXT,
    LOGIN_MGT TEXT,
    OS_VERSION TEXT,
    IN_SSCD INTEGER
);

CREATE TABLE PORTAL_SOC_FW (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CID TEXT,
    CUSTOMER TEXT,
    LOCATION_DESC TEXT,
    IP TEXT,
    MGT_PORT TEXT,
    SN TEXT,
    OSVERSION TEXT,
    LIC_EXPIRATION TEXT,
    IN_RANCID INTEGER,
    IN_SSCD INTEGER,
    IN_NETCOOL INTEGER,
    IN_PORTAL INTEGER
);

CREATE TABLE PORTAL_SOC_FW_TRANSITION (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CID TEXT,
    CUSTOMER TEXT,
    LOCATION_DESC TEXT,
    IP TEXT,
    MGT_PORT TEXT,
    SN TEXT,
    OSVERSION TEXT,
    LIC_EXPIRATION TEXT,
    IN_RANCID INTEGER,
    IN_NETCOOL INTEGER,
    IN_SSCD INTEGER
);

CREATE TABLE RANCID_DEVICES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CID TEXT,
    CIDNUM INTEGER,
    CUSTOMER TEXT,
    LOCATION_DESC TEXT,
    IP_DCN TEXT,
    OSVERSION TEXT,
    BACKUP_STATUS TEXT,
    BACKUP_DATE TEXT,
    VENDOR TEXT,
    IN_PORTAL INTEGER,
    IN_SSCD INTEGER,
    IN_NETCOOL INTEGER,
    IN_RANCID INTEGER
);

CREATE TABLE NETCOOL_DEVICES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    IP_DCN TEXT,
    CUSTOMER TEXT,
    CID TEXT,
    CPE_MODEL TEXT,
    COUNTRY TEXT,
    CITY TEXT,
    STATE_NAME TEXT,
    LOCATION_DESC TEXT,
    DEPARTMENT TEXT,
    IN_NETCOOL INTEGER,
    IN_PORTAL INTEGER,
    IN_SSCD INTEGER,
    IN_RANCID INTEGER
);

CREATE TABLE NETCOOL_FW (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    IP_DCN TEXT,
    CUSTOMER TEXT,
    CID TEXT,
    CPE_MODEL TEXT,
    COUNTRY TEXT,
    CITY TEXT,
    STATE_NAME TEXT,
    LOCATION_DESC TEXT,
    DEPARTMENT TEXT,
    IN_NETCOOL INTEGER,
    IN_PORTAL INTEGER,
    IN_SSCD INTEGER,
    IN_RANCID INTEGER
);

CREATE TABLE CONSOLIDATED_FW (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CONFIG_ITEM TEXT,
    CLASS_DESC TEXT,
    LOCATION_ADDRESS TEXT,
    CUSTOMER_NAME TEXT,
    IP TEXT,
    IN_SSCD INTEGER,
    IN_NETCOOL INTEGER,
    IN_RANCID INTEGER,
    IN_PORTAL INTEGER,
    BACKUP_STATUS TEXT,
    BACKUP_DATE TEXT,
    PING_ANSWER INTEGER,
    NMAP_PORTS TEXT,
    LOGIN_MGT TEXT,
    LOGIN_API TEXT,
    HOSTNAME TEXT,
    MODEL TEXT,
    SN TEXT,
    OS_VERSION TEXT
);

